# Generated by Django 5.1.1 on 2024-10-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_testtable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testtable',
            table='test_table',
        ),
    ]
