# Generated by Django 5.1.1 on 2024-10-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_testtable_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testtable',
            table='sujal_table',
        ),
    ]
