# Generated by Django 5.1.1 on 2024-10-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_testtable_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testtable',
            table='sujal_efgh',
        ),
    ]
